- .github/workflows/dependabot-approve-and-merge.yaml
The logs in runs https://github.com/opentdf/otdfctl/actions/runs/8617910910/job/23619038200 & https://github.com/opentdf/otdfctl/actions/runs/8617908584/job/23619030267 indicate the action would have auto-merged and approved the dependabot PRs.
> chore(dependabot): update dependabot GHA to actually merge and approve minor/patch bumps and log otherwise

- cmd/auth.go
- cmd/config.go
- cmd/dev-selectors.go
- cmd/dev.go
- cmd/interactive.go
- cmd/policy.go
- cmd/root.go
- docs/man/_index.md
- go.mod
- go.sum
- internal/config/config.go
- main.go
- pkg/handlers/selectors.go
- Allow root command to be exported for ease of consumption in wrapper CLIs and processes
- Add new `ExecuteWithBootstrap` command for injection of a separate config 
- Remove `config-file` CLI flag suffering from race condition between Viper & Cobra loading first in our "update format" flow
> feat(core): make root command exportable and add config bootstrapping

- cmd/auth-clearCachedCredentials.go
- cmd/auth-clientCredentials.go
- cmd/auth-printAccessToken.go
- cmd/auth.go
- docs/man/auth/clear-cached-credentials.md
- docs/man/auth/print-access-token.md
- pkg/cli/handlers.go
- pkg/handlers/auth.go
- pkg/handlers/sdk.go
1. Adds `print-access-token` subcommand In the style of gcloud's CLI: https://cloud.google.com/sdk/gcloud/reference/auth/print-access-token
2. Adds `clear-cached-credentials` subcommand to remove any client ID, secret, and token found on the native OS
Closes #136
> feat(core): enhance auth functionalities of CLI

- cmd/dev.go
- cmd/root.go
- docs/man/_index.md
- pkg/handlers/sdk.go
Discussion about change https://github.com/opentdf/otdfctl/pull/155#discussion_r1602201648
> fix: change name of --insecure flag to --tls-no-verify

- go.mod
- pkg/cli/tabular.go
Closes #194 
```shell
jakevanvorhis:otdfctl jake.vanvorhis$ go run . policy attributes list --host http://localhost:8080
SUCCESS   Found otdfctl policy attributes list                                                                                                                       
╭─────────────────────────────────────┬─────────────────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬────────┬────────┬────────╮
│ID                                   │Namespace                    │Name                  │Rule           │Values         │Active         │Labels  │Created…│Updated…│
├─────────────────────────────────────┼─────────────────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼────────┼────────┼────────┤ …
```
> fix(core): fix LIST command helper output to include all subcommands up to root

- pkg/cli/tabular.go
> fix(core): fix single resource get output

- go.mod
The version of Go used was updated to 1.22.5 from 1.22.4 in the project's go.mod file. This change ensures the project is running on the latest stable release of Go for the best possible performance and security. see https://pkg.go.dev/vuln/GO-2024-2963
> chore(ci): Go 1.22.5

- pkg/cli/errors.go
Closes https://github.com/opentdf/otdfctl/issues/113
Resolve issue where `cli.ExitWithError` was not exiting the process and panicking in some scenarious because `nil` errors were passed into it.
> fix(core): fix error handler to avoid metadata labels panic

- cmd/dev.go
- don't skip newline characters
- tested locally with replace directive from internal project
- This is causing failures when decrypting piped input if the TDF bytes happens to contain one of a small set of stop characters - which is very likely for larger files but not too likely for very small files so we hadn't noticed
> fix(core): Fixes piped input parser on decrypt

- cmd/policy-attributeValues.go
- pkg/cli/confirm.go
- pkg/cli/sdkHelpers.go
- pkg/handlers/attributeValues.go
Downstream of platform issues [984](https://github.com/opentdf/platform/issues/984) & [1095](https://github.com/opentdf/platform/issues/1095) to deprecate attribute value members.
> fix(core): remove deprecated policy members

- cmd/policy-subjectConditionSets.go
Resolves #244 
Utilizes protojson and json.RawMessage for arrays of protos to properly marshal/unmarshal protos as json. The prior implementation seemingly ignored fields at times and this is the approach taken by the platform and recommended for proto marshaling.
> fix(core): fix subject-condition-sets Create/Update with protojson marshaling

- cmd/policy-subjectConditionSets.go
- docs/man/policy/subject-condition-sets/update.md
> feat(core): support update of SCS read from JSON file

- cmd/profile.go
- pkg/profiles/profile.go
fixes nil pointer panic on `profile set-default`
> fix(core): nil panic on set-default

- tests/encrypt-decrypt.bats
Related to https://github.com/opentdf/platform/issues/1359
> feat(ci): attr e2e tests with mixed casing

- .github/workflows/ci.yaml
- cmd/kas-registry.go
- docs/man/policy/kas-registry/_index.md
- docs/man/policy/kas-registry/create.md
- docs/man/policy/kas-registry/delete.md
- docs/man/policy/kas-registry/update.md
- tests/kas-registry.bats
> feat(core): kasr cached keys to deprecate local

- .gitignore
- cmd/auth-login.go
- cmd/auth-logout.go
- cmd/root.go
- docs/man/_index.md
- pkg/auth/auth.go
- pkg/utils/http.go
With otdfctl leveraging zitadel module for oidc outside the scope of the sdk otdfctl needs to create a custom http client to ignore tls verification.
> fix: create new http client to ignore tls verification

- .github/spellcheck.ignore
- cmd/tdf-encrypt.go
- cmd/tdf-inspect.go
- docs/man/encrypt/_index.md
- go.mod
- go.sum
- pkg/handlers/nano-tdf.go
- pkg/handlers/tdf.go
- tests/encrypt-decrypt.bats
- this enables the optional 'ecdsa binding' feature in nanotdf containers
> feat(core): add ecdsa-binding encrypt flag

- .github/workflows/ci.yaml
- e2e/action.yaml
- go.mod
- go.sum
- pkg/auth/auth.go
Resolves #371 
Unblocked by https://github.com/opentdf/platform/issues/1530
Chicken and egg problem at the moment:
When referencing the changes to _not run the platform_ in `otdfctl/e2e/action.yaml` by referencing the branch for the run, we [have a passing job](https://github.com/opentdf/otdfctl/actions/runs/10779107822/job/29891886738?pr=369) but we need to merge this in to have it pass compatibly.
Evidence the `platform` can run the tests on a PR branch there against `main` in `otdfctl`: https://github.com/opentdf/platform/actions/runs/10780058471/job/29894940400?pr=1526
> feat(ci): reusable platform composite action in e2e tests

- cmd/policy-subjectMappings.go
- docs/man/policy/subject-mappings/delete.md
- e2e/setup_suite.bash
- e2e/subject-mapping.bats
Resolves #329 
- various `shellcheck` lint fixes found locally
- a `--force` delete flag on SM
- validation that at least one SCS flag value was added on create
> feat(ci): add e2e tests for subject mappings, support for --force delete

- cmd/dev.go
- cmd/policy-resourceMappings.go
- docs/man/policy/resource-mappings/create.md
- docs/man/policy/resource-mappings/delete.md
- docs/man/policy/resource-mappings/get.md
- docs/man/policy/resource-mappings/update.md
- e2e/encrypt-decrypt.bats
- e2e/kas-grants.bats
- e2e/namespaces.bats
- e2e/resource-mapping.bats
> feat(core): resource mappings LIST fix, delete --force support, and e2e tests

- cmd/policy-resourceMappings.go
Due to changes made in https://github.com/opentdf/platform/pull/1422 to only return an object with the ID for delete operations, we need to update the otdfctl Resource Mapping delete operation to make a Get request from the DB before deletion of the record.  The object returned from the Get is then used for the user-friendly CLI output of the whole object.
> feat(core): Update Resource Mapping delete to use get before delete for cli output

- go.mod
- go.sum
This pr updates the go sdk to 0.3.19 so it picks up the fixes to the GetTdfType function for detecting nanotdf or base tdf.
> fix: updates sdk to 0.3.19 with GetTdfType fixes

- .github/spellcheck.ignore
- cmd/kas-registry.go
- cmd/policy-attributeNamespaces.go
- cmd/policy-attributes.go
- cmd/policy-resourceMappings.go
- cmd/policy-subjectConditionSets.go
- cmd/policy-subjectMappings.go
- docs/man/policy/subject-condition-sets/prune.md
- e2e/subject-condition-sets.bats
- pkg/handlers/subjectConditionSets.go
Closes https://github.com/opentdf/otdfctl/issues/235
> feat(core): subject condition set prune

- cmd/policy-subjectMappings.go
- e2e/subject-mapping.bats
required a change in the platform to expose the value's FQN on SM list: https://github.com/opentdf/platform/pull/1796
> fix(core): sm list should provide value fqn instead of just value string

- docs/man/policy/kas-registry/create.md
change markdown example code block from json5 to json in KASR create help manual for easier copy/paste into the CLI
> fix(core): kasr creation JSON example

- .github/workflows/ci.yaml
- .golangci.yaml
- cmd/config.go
Handles golangci-lint v2 upgrade to unblock CI pipeline.
Detected lint issues were not introduced by this PR and will be handled separately: https://github.com/opentdf/otdfctl/issues/529
> chore(ci): use latest golangci-lint in CI

- .github/workflows/ci.yaml
This prevents failing to detect a major breaking change in a github action dependency bump from dependabot, as happened recently with the `golangci-lint` action upgrading to require v2.
> fix(ci): ci job should run on changes to GHA

- .github/release-please.json
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- pkg/config/config.go
- Adds xtest workflow, for testing against LTS version of otdfctl and platform backend
- Lets release-please set the baked-in version field, to allow easier builds from source and as a library
- Notably, this slightly improves error output in the xtest logs
> chore(ci): Enable testing against old releases

- pkg/handlers/sdk.go
include the scheme when passing the url to the sdk constructor
> fix(main): Pass the full url when building the sdk object

- cmd/tdf-decrypt.go
- docs/man/decrypt/_index.md
- e2e/encrypt-decrypt.bats
- go.mod
- go.sum
- pkg/handlers/sdk.go
- pkg/handlers/tdf.go
- option to add a custom kas allowlist
- option to ignore the kas allowlist
- bats for the above options for tdf3 and nano
> feat(core): KAS allowlist options

- cmd/kas-grants.go
- cmd/kas-registry.go
- cmd/policy-attributeNamespaces.go
- cmd/policy-attributeValues.go
- cmd/policy-attributes.go
- cmd/policy-subjectConditionSets.go
- pkg/handlers/attribute.go
- pkg/handlers/attributeValues.go
- pkg/handlers/kas-registry.go
- pkg/handlers/namespaces.go
- pkg/handlers/sdk.go
- pkg/handlers/subjectConditionSets.go
- pkg/handlers/subjectmappings.go
- tui/appMenu.go
- tui/attributeList.go
- tui/attributeView.go
- tui/labelList.go
- tui/labelUpdate.go
Updates handler struct to use passed-in context from the Cobra `cmd` struct
> feat(core): DSPX-18 clean up Go context usage to follow best practices

- cmd/kas-keys.go
- docs/man/policy/kas-registry/key/rotate.md
- e2e/kas-keys.bats
- pkg/handlers/kas-keys.go
- Add rotate key command
- Refactor duplicate code between create/rotate commands
> feat(core): Rotate key.

- pkg/config/config.go
version in `pkg/config/config.go` should match version in `.github/.release-please-manifest.json` for release-please
> chore(ci): Fix version mismatch

- .github/workflows/ci.yaml
- skips currently failing lts (0.15.0) tag
> chore(ci): Let xtest validate against latest

- cmd/policy-registeredResources.go
- docs/man/policy/registered-resources/values/update.md
- e2e/registered-resources.bats
- pkg/cli/confirm.go
Adds a confirmation prompt to the registered resource values update command to notify users that any existing action attribute values will be replaced by any new ones provided to the command. Can be ignored using a new `--force` flag added in this PR as well.
> feat(core): Registered Resources - action attribute values update confirmation

- .github/workflows/main-dependency-review.yaml
The `base-ref` for dependency review is typically the target branch you're merging into. This results in dependency-review alerting on any changed dependencies which may have CVE's.
By using `main` as our `base-ref`, we are now also validating that the target branch has adopted all necessary security updates that were adopted within the `main` branch.
This will help ensure `release` branches have adopted all necessary security fixes.
> chore: backport-0.24: Add dependency-review workflow that always targets `main` (#640)
