opentdf/otdfctl

README.md
=> docs: update references to otdfctl

cmd/policy.go, cmd/root.go, docs/man/_index.md, docs/man/policy/_index.md
=> fix(core): move json global flag to the policy subcommand where it is always relevant

cmd/dev.go, cmd/policy-attributeNamespaces.go, cmd/policy-attributeValues.go, cmd/policy-attributes.go, cmd/policy-resourceMappings.go, cmd/policy-subjectConditionSets.go, cmd/policy-subject_mappings.go, go.mod, pkg/cli/sdkHelpers.go
Namespaces:
Attributes:
Values:
Subject Mappings:
Subject Condition Sets:
Resource Mappings:
and LIST cmds
=> feat(core): add metadata to table output

README.md
Adds required pre-reqs to README
=> docs(core): Add pre-reqs to README

cmd/auth-clientCredentials.go, pkg/handlers/auth.go
=> fix(core): pull correct flag for tls-no-verify on auth cmd

cmd/dev-selectors.go
=> fix(demo): remove selectors command while platform undergoes changes

cmd/auth-clientCredentials.go, cmd/dev.go
=> fix(core): sync up auth client credentials flags

cmd/dev-selectors.go, cmd/dev.go, cmd/kas-grants.go, cmd/kas-registry.go, cmd/policy-attributeNamespaces.go, cmd/policy-attributeValues.go, cmd/policy-attributes.go, cmd/policy-resourceMappings.go, cmd/policy-subjectConditionSets.go, cmd/policy-subject_mappings.go, go.mod, go.sum, pkg/cli/style.go, pkg/cli/table.go, pkg/cli/tabular.go
=> feat: improve table experience with more dynamic library

cmd/policy-attributeValues.go, pkg/cli/sdkHelpers.go
Closes https://github.com/opentdf/otdfctl/issues/217
=> fix(core): values list should properly render table output

cmd/kas-grants.go
=> fix: use right kas-grants flag names when retrieving values

LICENSE
Resolves https://github.com/opentdf/otdfctl/issues/246
=> feat(core): add license

cmd/kas-registry.go, cmd/policy-subjectConditionSets.go, docs/man/policy/subject-condition-sets/_index.md
=> fix(core): fix regression where SCS list unavailable

cmd/kas-grants.go, docs/man/policy/kas-grants/_index.md, docs/man/policy/kas-grants/assign.md, docs/man/policy/kas-grants/remove.md, docs/man/policy/kas-grants/unassign.md, docs/man/policy/kas-registry/_index.md, docs/man/policy/kas-registry/create.md
=> docs(core): KAS grants docs

docs/man/policy/subject-condition-sets/_index.md, docs/man/policy/subject-condition-sets/create.md, docs/man/policy/subject-mappings/_index.md
=> docs(core): provide subject condition set example

cmd/profile.go, pkg/profiles/errors.go, pkg/profiles/globalConfig.go, pkg/profiles/profile.go
=> fix(core): warn and do now allow deletion of default profile

docs/man/policy/kas-registry/create.md
=> fix(core): remove documentation that cached kas pubkey is base64

cmd/kas-grants.go, cmd/kas-registry.go, cmd/policy-attributeNamespaces.go, cmd/policy-attributeValues.go, cmd/policy-attributes.go, cmd/policy-resourceMappings.go, cmd/policy-subjectConditionSets.go, cmd/policy-subject_mappings.go, cmd/profile.go, cmd/root.go, e2e/auth.bats, e2e/kas-grants.bats, e2e/namespaces.bats, pkg/auth/auth.go, pkg/auth/errors.go, pkg/cli/errors.go, pkg/cli/flagValues.go, pkg/profiles/profile.go
Resolves #377 
Resolves #376 
Resolves #380
=> fix(core): GOOS, error message fixes

cmd/policy-subjectConditionSets.go, docs/man/policy/subject-condition-sets/delete.md, e2e/subject-condition-sets.bats
=> feat(ci): add tests for subject condition sets, and --force delete flag

pkg/profiles/profileConfig.go, pkg/utils/validators.go
=> fix(core): remove trailing slashes on host/platformEndpoint

.github/workflows/backport.yaml, .github/workflows/create-release-branch.yaml, .github/workflows/release.yaml
Secrets need to be passed to reusable workflows.
=> chore(ci): Fix secrets passing for reusable workflows

e2e/attributes.bats, e2e/base-key.bats, e2e/namespaces.bats, pkg/config/config.go
- Comment out tests for platform merges.
=> chore(core): Comment out tests to unblock platform merges

cmd/base-keys.go, cmd/kas-keys.go, cmd/policy-attributeNamespaces.go, cmd/policy-attributeValues.go, cmd/policy-attributes.go, e2e/attributes.bats, e2e/base-key.bats, e2e/namespaces.bats, go.mod, go.sum, pkg/cli/sdkHelpers.go, pkg/handlers/base-keys.go
1. Uncomment out code that was previously commented out 
2. Pull in new protocol/go version with structure changes.
3. Remove unneeded key ids column from attributes display.
=> feat(core): Uncomment code and pull in new protos.

docs/man/policy/attributes/key/_index.md, docs/man/policy/attributes/namespaces/key/_index.md, docs/man/policy/attributes/values/key/_index.md, docs/man/policy/kas-registry/key/_index.md, docs/man/policy/kas-registry/key/base/_index.md, docs/man/policy/key-management/_index.md, docs/man/policy/key-management/provider/_index.md
=> feat(core): Unhide key commands.

.github/workflows/codeql.yaml, cmd/kas-keys.go, docs/man/policy/kas-registry/key/unsafe/_index.md, docs/man/policy/kas-registry/key/unsafe/delete.md, e2e/attributes.bats, e2e/kas-keys-mappings.bats, e2e/kas-keys.bats, e2e/key-base.bats, e2e/namespaces.bats, e2e/otdfctl-utils.sh, go.mod, go.sum, pkg/cli/confirm.go, pkg/handlers/kas-keys.go
- Add the ability to delete kas keys
- Refactor a couple common commands into **otdfctl-utils.sh**
- Delete keys where possible
=> feat(core): Delete kas keys
